### ISSUE TITLE
ISSUE: Unlocking doesn't decrement Unlock events

### ISSUE THREAD

**Issue by rbauman70** [FutureTense/keymaster#128]
With a lock code enabled, Enforce pin limit enabled and Unlock events set to 1, using the keypad code on a BE469ZP doesn't cause the Unlock events counter to decrement.  The lock code never becomes disabled in HA or on the lock.

Versions:
Home Assistant Core: core-2021.3.3
ZWave: zwavejs2mqtt, Zwavejs version 6.6.0, Zwavejs-server version 1.1.0, websockets enabled, MQTT disabled.
Keymaster version 0.0.27, installed from HACS

Here are the zwavejs and keymaster events posted for a manual and keypad lock and unlock operation:

Event 6 fired 9:50 AM:
{
    "event_type": "zwave_js_event",
    "data": {
        "type": "notification",
        "domain": "zwave_js",
        "node_id": 3,
        "home_id": 3221914550,
        "device_id": "4c13f86d958d890f6c30c6a99e0da63f",
        "label": "Manual unlock operation",
        "parameters": {}
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-13T14:50:46.966844+00:00",
    "context": {
        "id": "578e9db597953b47460f8bcfb11e408d",
        "parent_id": null,
        "user_id": null
    }
}
Event 5 fired 9:50 AM:
{
    "event_type": "zwave_js_event",
    "data": {
        "type": "notification",
        "domain": "zwave_js",
        "node_id": 3,
        "home_id": 3221914550,
        "device_id": "4c13f86d958d890f6c30c6a99e0da63f",
        "label": "Manual lock operation",
        "parameters": {}
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-13T14:50:41.986789+00:00",
    "context": {
        "id": "a311088ba08837d193fe83d3ef97e2e2",
        "parent_id": null,
        "user_id": null
    }
}
Event 4 fired 9:50 AM:
{
    "event_type": "zwave_js_event",
    "data": {
        "type": "notification",
        "domain": "zwave_js",
        "node_id": 3,
        "home_id": 3221914550,
        "device_id": "4c13f86d958d890f6c30c6a99e0da63f",
        "label": "Keypad unlock operation",
        "parameters": {
            "userId": 3
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-13T14:50:34.437041+00:00",
    "context": {
        "id": "c8215aadab40a57e391444be03d58627",
        "parent_id": null,
        "user_id": null
    }
}
Event 3 fired 9:50 AM:
{
    "event_type": "zwave_js_event",
    "data": {
        "type": "notification",
        "domain": "zwave_js",
        "node_id": 3,
        "home_id": 3221914550,
        "device_id": "4c13f86d958d890f6c30c6a99e0da63f",
        "label": "Keypad lock operation",
        "parameters": {}
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-13T14:50:29.114754+00:00",
    "context": {
        "id": "2e73be27a2d0c98026fa206c4c8dcfeb",
        "parent_id": null,
        "user_id": null
    }
}

 Event 3 fired 9:50 AM:
{
    "event_type": "keymaster_lock_state_changed",
    "data": {
        "lockname": "frontdoor",
        "entity_id": "lock.touchscreen_deadbolt_z_wave_plus_current_lock_mode_frontdoor",
        "state": "unlocked",
        "action_text": "Manual unlock operation",
        "code_slot": 0,
        "code_slot_name": ""
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-13T14:50:46.967883+00:00",
    "context": {
        "id": "454242aaf2b8aeea3ce0e7338fe2ad91",
        "parent_id": null,
        "user_id": null
    }
}
Event 2 fired 9:50 AM:
{
    "event_type": "keymaster_lock_state_changed",
    "data": {
        "lockname": "frontdoor",
        "entity_id": "lock.touchscreen_deadbolt_z_wave_plus_current_lock_mode_frontdoor",
        "state": "locked",
        "action_text": "Manual lock operation",
        "code_slot": 0,
        "code_slot_name": ""
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-13T14:50:41.987761+00:00",
    "context": {
        "id": "2d04a443cf1fa5915d500af9dd0c5b9e",
        "parent_id": null,
        "user_id": null
    }
}
Event 1 fired 9:50 AM:
{
    "event_type": "keymaster_lock_state_changed",
    "data": {
        "lockname": "frontdoor",
        "entity_id": "lock.touchscreen_deadbolt_z_wave_plus_current_lock_mode_frontdoor",
        "state": "unlocked",
        "action_text": "Keypad unlock operation",
        "code_slot": 3,
        "code_slot_name": "Limited"
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-13T14:50:34.438140+00:00",
    "context": {
        "id": "d1d7c30f5a51f8e131b5d73cb9cd2035",
        "parent_id": null,
        "user_id": null
    }
}
Event 0 fired 9:50 AM:
{
    "event_type": "keymaster_lock_state_changed",
    "data": {
        "lockname": "frontdoor",
        "entity_id": "lock.touchscreen_deadbolt_z_wave_plus_current_lock_mode_frontdoor",
        "state": "locked",
        "action_text": "Keypad lock operation",
        "code_slot": 0,
        "code_slot_name": ""
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-13T14:50:29.116742+00:00",
    "context": {
        "id": "e8b31d22a12b53821789557aed29455d",
        "parent_id": null,
        "user_id": null
    }
}

[frontdoor.zip](https://github.com/FutureTense/keymaster/files/6135029/frontdoor.zip)

**Comment by raman325** [comment]
I believe I have fixed this with the linked PR. I will merge this in a sec but it may be a couple of days before the new release, I'd like to resolve some of the other issues reported before we release again

**Comment by w0lf3h** [comment]
Quick test of one of my BE469ZP locks on v0.0.28 was still giving me this issue. No time to grab logs before work, but I'll do it tomorrow morning unless @rbauman70 beats me to it. 😛

**Comment by raman325** [comment]
Yes please do share logs, and also do me a favor and listen to the `keymaster_lock_state_changed` event, unlock or lock your lock with a PIN, and share the event data for that event as well. That will help me diagnose what could be happening

**Comment by rbauman70** [comment]
Yeah, I can confirm it's still not working in 0.0.28.  Here are the zwave and keymaster event logs:

Event 3 fired 5:42 PM:
{
    "event_type": "zwave_js_event",
    "data": {
        "type": "notification",
        "domain": "zwave_js",
        "node_id": 3,
        "home_id": 3221914550,
        "device_id": "4c13f86d958d890f6c30c6a99e0da63f",
        "label": "Manual unlock operation",
        "parameters": {}
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-17T21:42:05.236187+00:00",
    "context": {
        "id": "16cc2f552b75c09906761f4b2c15676d",
        "parent_id": null,
        "user_id": null
    }
}
Event 2 fired 5:41 PM:
{
    "event_type": "zwave_js_event",
    "data": {
        "type": "notification",
        "domain": "zwave_js",
        "node_id": 3,
        "home_id": 3221914550,
        "device_id": "4c13f86d958d890f6c30c6a99e0da63f",
        "label": "Manual lock operation",
        "parameters": {}
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-17T21:41:58.550304+00:00",
    "context": {
        "id": "45cd02eee7e413f68698a413d630cbbe",
        "parent_id": null,
        "user_id": null
    }
}
Event 1 fired 5:41 PM:
{
    "event_type": "zwave_js_event",
    "data": {
        "type": "notification",
        "domain": "zwave_js",
        "node_id": 3,
        "home_id": 3221914550,
        "device_id": "4c13f86d958d890f6c30c6a99e0da63f",
        "label": "Keypad unlock operation",
        "parameters": {
            "userId": 3
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-17T21:41:45.765445+00:00",
    "context": {
        "id": "581210761b6b1b3c9cc8fb7d6749581b",
        "parent_id": null,
        "user_id": null
    }
}
Event 0 fired 5:41 PM:
{
    "event_type": "zwave_js_event",
    "data": {
        "type": "notification",
        "domain": "zwave_js",
        "node_id": 3,
        "home_id": 3221914550,
        "device_id": "4c13f86d958d890f6c30c6a99e0da63f",
        "label": "Keypad lock operation",
        "parameters": {}
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-17T21:41:39.799786+00:00",
    "context": {
        "id": "2c9d9bc7628b1c728d94e93600029127",
        "parent_id": null,
        "user_id": null
    }
}

Event 3 fired 5:42 PM:
{
    "event_type": "keymaster_lock_state_changed",
    "data": {
        "notification_source": "event",
        "lockname": "frontdoor",
        "entity_id": "lock.touchscreen_deadbolt_z_wave_plus_current_lock_mode_frontdoor",
        "state": "unlocked",
        "action_text": "Manual unlock operation",
        "code_slot": 0,
        "code_slot_name": ""
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-17T21:42:05.238068+00:00",
    "context": {
        "id": "f1cc37e724c2ecec3ea609dce2b4a4cd",
        "parent_id": null,
        "user_id": null
    }
}
Event 2 fired 5:41 PM:
{
    "event_type": "keymaster_lock_state_changed",
    "data": {
        "notification_source": "event",
        "lockname": "frontdoor",
        "entity_id": "lock.touchscreen_deadbolt_z_wave_plus_current_lock_mode_frontdoor",
        "state": "locked",
        "action_text": "Manual lock operation",
        "code_slot": 0,
        "code_slot_name": ""
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-17T21:41:58.552125+00:00",
    "context": {
        "id": "e96e31658fdb6d3a5002501f9d63bb96",
        "parent_id": null,
        "user_id": null
    }
}
Event 1 fired 5:41 PM:
{
    "event_type": "keymaster_lock_state_changed",
    "data": {
        "notification_source": "event",
        "lockname": "frontdoor",
        "entity_id": "lock.touchscreen_deadbolt_z_wave_plus_current_lock_mode_frontdoor",
        "state": "unlocked",
        "action_text": "Keypad unlock operation",
        "code_slot": 3,
        "code_slot_name": "Limited"
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-17T21:41:45.766521+00:00",
    "context": {
        "id": "57f3703c07eb2114f04386e80cabae3d",
        "parent_id": null,
        "user_id": null
    }
}
Event 0 fired 5:41 PM:
{
    "event_type": "keymaster_lock_state_changed",
    "data": {
        "notification_source": "event",
        "lockname": "frontdoor",
        "entity_id": "lock.touchscreen_deadbolt_z_wave_plus_current_lock_mode_frontdoor",
        "state": "locked",
        "action_text": "Keypad lock operation",
        "code_slot": 0,
        "code_slot_name": ""
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-17T21:41:39.800828+00:00",
    "context": {
        "id": "f6f1219cbf2d16bdb9a14d1417384c7c",
        "parent_id": null,
        "user_id": null
    }
}

**Comment by raman325** [comment]
thanks, did you regenerate your package files before testing? this was a template change not a code change. I tested the logic and everything seems to work as I would expect once I regenerated package files. I also just tested this on my lock using `zwave_js` and it decremented fine

**Comment by rbauman70** [comment]
That worked. Unlock events was decremented.  I had restarted HA a number of times after updating in HACS to the new keymaster version but I had not gone through Integrations..keymaster..options..submit again.  Thanks for getting it working.

**Comment by w0lf3h** [comment]
Aha. My issue was the opposite. I didn't restart HA after package regeneration. After the restart, everything is working as intended. Thanks @raman325 :)
